
//**********************************************************************`
//* This is an include file generated by EtwPlusTool.                  *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once
#pragma pack(push, 16)

#include "EtwPlus.h"

#if defined(__cplusplus)
extern "C" {
#endif

// Field Descriptors, used in the ETX_EVENT_DESCRIPTOR array below
//
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_AchievementEvent_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_AchievementUpdate_Fields[5] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_CharacterEvent_Fields[20] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_CreationEvent_Fields[19] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_CreationProgress_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Double,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_EnemyDefeated_Fields[16] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_GameProgress_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Float,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_ItemUsed_Fields[11] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_MediaUsage_Fields[27] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UInt32,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UInt64,0},{EtxFieldType_UInt32,0},{EtxFieldType_Float,0},{EtxFieldType_UInt64,0},{EtxFieldType_UInt64,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Float,0},{EtxFieldType_UInt32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_MissionProgress_Fields[5] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int64,0},{EtxFieldType_Double,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_MultiplayerRoundEnd_Fields[11] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Float,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_MultiplayerRoundStart_Fields[9] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_ObjectiveEnd_Fields[9] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_ObjectiveStart_Fields[8] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_PageAction_Fields[9] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_PageView_Fields[9] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_PlayerDefeated_Fields[15] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_PlayerMatchEvent_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_PlayerSessionEnd_Fields[7] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_PlayerSessionPause_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_PlayerSessionResume_Fields[6] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_PlayerSessionStart_Fields[6] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_PlayerSpawned_Fields[12] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0},{EtxFieldType_Float,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_PresenceEvent_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_RankmatchEvent_Fields[20] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_ReplayEvent_Fields[19] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_SectionEnd_Fields[8] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_SectionStart_Fields[7] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_GUID,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_Int32,0},{EtxFieldType_Int32,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_VersusProgress_Fields[4] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_Int64,0}};
EXTERN_C __declspec(selectany) ETX_FIELD_DESCRIPTOR NBGI_22CB4DAA_ViewOffer_Fields[5] = {{EtxFieldType_UnicodeString,0},{EtxFieldType_UnicodeString,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0},{EtxFieldType_GUID,0}};

// Event name mapping
//
#define AchievementEvent_value 1
#define AchievementUpdate_value 2
#define CharacterEvent_value 3
#define CreationEvent_value 4
#define CreationProgress_value 5
#define EnemyDefeated_value 6
#define GameProgress_value 7
#define ItemUsed_value 8
#define MediaUsage_value 9
#define MissionProgress_value 10
#define MultiplayerRoundEnd_value 11
#define MultiplayerRoundStart_value 12
#define ObjectiveEnd_value 13
#define ObjectiveStart_value 14
#define PageAction_value 15
#define PageView_value 16
#define PlayerDefeated_value 17
#define PlayerMatchEvent_value 18
#define PlayerSessionEnd_value 19
#define PlayerSessionPause_value 20
#define PlayerSessionResume_value 21
#define PlayerSessionStart_value 22
#define PlayerSpawned_value 23
#define PresenceEvent_value 24
#define RankmatchEvent_value 25
#define ReplayEvent_value 26
#define SectionEnd_value 27
#define SectionStart_value 28
#define VersusProgress_value 29
#define ViewOffer_value 30

// Event Descriptor array
//
EXTERN_C __declspec(selectany) ETX_EVENT_DESCRIPTOR NBGI_22CB4DAAEvents[30] =  {
    {{ 1, 1, 0, 0, 0, 0, 0x0 }, "AchievementEvent", "0.7.IGB-2.1", NBGI_22CB4DAA_AchievementEvent_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 2, 0, 0, 0, 0, 0, 0x0 }, "AchievementUpdate", "0.7.IGAU-1.0", NBGI_22CB4DAA_AchievementUpdate_Fields, 5, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 3, 1, 0, 0, 0, 0, 0x0 }, "CharacterEvent", "0.7.IGB-2.1", NBGI_22CB4DAA_CharacterEvent_Fields, 20, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 4, 1, 0, 0, 0, 0, 0x0 }, "CreationEvent", "0.7.IGB-2.1", NBGI_22CB4DAA_CreationEvent_Fields, 19, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 5, 1, 0, 0, 0, 0, 0x0 }, "CreationProgress", "0.7.IGB-2.1", NBGI_22CB4DAA_CreationProgress_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 6, 0, 0, 0, 0, 0, 0x0 }, "EnemyDefeated", "0.7.IGED-2.0", NBGI_22CB4DAA_EnemyDefeated_Fields, 16, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 7, 0, 0, 0, 0, 0, 0x0 }, "GameProgress", "0.7.IGGP-2.0", NBGI_22CB4DAA_GameProgress_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 8, 0, 0, 0, 0, 0, 0x0 }, "ItemUsed", "0.7.IGIU-2.0", NBGI_22CB4DAA_ItemUsed_Fields, 11, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 9, 0, 0, 0, 0, 0, 0x0 }, "MediaUsage", "0.7.MAUMU-2.0", NBGI_22CB4DAA_MediaUsage_Fields, 27, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 10, 1, 0, 0, 0, 0, 0x0 }, "MissionProgress", "0.7.IGB-2.1", NBGI_22CB4DAA_MissionProgress_Fields, 5, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 11, 0, 0, 0, 0, 0, 0x0 }, "MultiplayerRoundEnd", "0.7.IGMRE-2.0", NBGI_22CB4DAA_MultiplayerRoundEnd_Fields, 11, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 12, 0, 0, 0, 0, 0, 0x0 }, "MultiplayerRoundStart", "0.7.IGMRS-2.0", NBGI_22CB4DAA_MultiplayerRoundStart_Fields, 9, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 13, 0, 0, 0, 0, 0, 0x0 }, "ObjectiveEnd", "0.7.IGOE-3.0", NBGI_22CB4DAA_ObjectiveEnd_Fields, 9, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 14, 0, 0, 0, 0, 0, 0x0 }, "ObjectiveStart", "0.7.IGOS-2.0", NBGI_22CB4DAA_ObjectiveStart_Fields, 8, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 15, 0, 0, 0, 0, 0, 0x0 }, "PageAction", "0.7.IGPA-1.0", NBGI_22CB4DAA_PageAction_Fields, 9, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 16, 0, 0, 0, 0, 0, 0x0 }, "PageView", "0.7.IGPV-1.0", NBGI_22CB4DAA_PageView_Fields, 9, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 17, 0, 0, 0, 0, 0, 0x0 }, "PlayerDefeated", "0.7.IGPD-2.0", NBGI_22CB4DAA_PlayerDefeated_Fields, 15, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 18, 1, 0, 0, 0, 0, 0x0 }, "PlayerMatchEvent", "0.7.IGB-2.1", NBGI_22CB4DAA_PlayerMatchEvent_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 19, 0, 0, 0, 0, 0, 0x0 }, "PlayerSessionEnd", "0.7.IGPSE-2.0", NBGI_22CB4DAA_PlayerSessionEnd_Fields, 7, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 20, 0, 0, 0, 0, 0, 0x0 }, "PlayerSessionPause", "0.7.IGPSPA-2.0", NBGI_22CB4DAA_PlayerSessionPause_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 21, 0, 0, 0, 0, 0, 0x0 }, "PlayerSessionResume", "0.7.IGPSR-2.0", NBGI_22CB4DAA_PlayerSessionResume_Fields, 6, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 22, 0, 0, 0, 0, 0, 0x0 }, "PlayerSessionStart", "0.7.IGPSS-2.0", NBGI_22CB4DAA_PlayerSessionStart_Fields, 6, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 23, 0, 0, 0, 0, 0, 0x0 }, "PlayerSpawned", "0.7.IGPSP-2.0", NBGI_22CB4DAA_PlayerSpawned_Fields, 12, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 24, 1, 0, 0, 0, 0, 0x0 }, "PresenceEvent", "0.7.IGB-2.1", NBGI_22CB4DAA_PresenceEvent_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 25, 1, 0, 0, 0, 0, 0x0 }, "RankmatchEvent", "0.7.IGB-2.1", NBGI_22CB4DAA_RankmatchEvent_Fields, 20, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 26, 1, 0, 0, 0, 0, 0x0 }, "ReplayEvent", "0.7.IGB-2.1", NBGI_22CB4DAA_ReplayEvent_Fields, 19, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 27, 0, 0, 0, 0, 0, 0x0 }, "SectionEnd", "0.7.IGSE-2.0", NBGI_22CB4DAA_SectionEnd_Fields, 8, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 28, 0, 0, 0, 0, 0, 0x0 }, "SectionStart", "0.7.IGSS-2.0", NBGI_22CB4DAA_SectionStart_Fields, 7, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 29, 1, 0, 0, 0, 0, 0x0 }, "VersusProgress", "0.7.IGB-2.1", NBGI_22CB4DAA_VersusProgress_Fields, 4, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault },
    {{ 30, 0, 0, 0, 0, 0, 0x0 }, "ViewOffer", "0.7.IGVO-1.0", NBGI_22CB4DAA_ViewOffer_Fields, 5, 0, EtxEventEnabledState_Undefined, EtxEventEnabledState_ProviderDefault, EtxPopulationSample_Undefined, EtxPopulationSample_UseProviderPopulationSample, EtxEventLatency_Undefined, EtxEventLatency_ProviderDefault, EtxEventPriority_Undefined, EtxEventPriority_ProviderDefault }};

// Provider Descriptor for NBGI_22CB4DAA
//
EXTERN_C __declspec(selectany) ETX_PROVIDER_DESCRIPTOR NBGI_22CB4DAAProvider = {"NBGI_22CB4DAA", {0xe679d2db,0xe05d,0x4166,{0xa7,0x98,0x2f,0xab,0x31,0xa1,0x3c,0x94}}, 30, (ETX_EVENT_DESCRIPTOR*)&NBGI_22CB4DAAEvents, 0, EtxProviderEnabledState_Undefined, EtxProviderEnabledState_OnByDefault, 0, 100, EtxProviderLatency_Undefined, EtxProviderLatency_RealTime, EtxProviderPriority_Undefined, EtxProviderPriority_Critical};

// ETW handle for NBGI_22CB4DAA
//
EXTERN_C __declspec(selectany) REGHANDLE NBGI_22CB4DAAHandle = (REGHANDLE)0;

/*++

Routine Description:

    Register the provider with ETW+.

Arguments:
    
    None

Remarks:

    ERROR_SUCCESS if success or if the provider was already registered. 
    Otherwise, an error code.

--*/
#define EventRegisterNBGI_22CB4DAA() EtxRegister(&NBGI_22CB4DAAProvider, &NBGI_22CB4DAAHandle)

/*++

Routine Description:

    Unregister the provider from ETW+.

Arguments:
            None
Remarks:
    ERROR_SUCCESS if success or if the provider was not registered. 
    Otherwise, an error code.
--*/
#define EventUnregisterNBGI_22CB4DAA() EtxUnregister(&NBGI_22CB4DAAProvider, &NBGI_22CB4DAAHandle)

#define EventEnabledAchievementEvent() (TRUE)

// Entry point to log the event AchievementEvent
//
__inline
ULONG
EventWriteAchievementEvent(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int AchievementIndex)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_AchievementEvent 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_AchievementEvent];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &AchievementIndex, sizeof(AchievementIndex));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[0], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_AchievementEvent, EventData);
}
#define EventEnabledAchievementUpdate() (TRUE)

// Entry point to log the event AchievementUpdate
//
__inline
ULONG
EventWriteAchievementUpdate(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR AchievementId, __in const signed int PercentComplete)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_AchievementUpdate 5

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_AchievementUpdate];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (AchievementId != NULL) ? AchievementId : L"", (AchievementId != NULL) ? (ULONG)((wcslen(AchievementId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[4], &PercentComplete, sizeof(PercentComplete));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[1], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_AchievementUpdate, EventData);
}
#define EventEnabledCharacterEvent() (TRUE)

// Entry point to log the event CharacterEvent
//
__inline
ULONG
EventWriteCharacterEvent(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int CharacterId, __in const signed int Score, __in const signed int LBSTATE00, __in const signed int LBSTATE01, __in const signed int LBSTATE02, __in const signed int LBSTATE03, __in const signed int LBSTATE04, __in const signed int LBSTATE05, __in const signed int LBSTATE06, __in const signed int LBSTATE07, __in const signed int LBSTATE08, __in const signed int LBSTATE09, __in const signed int LBSTATE10, __in const signed int LBSTATE11, __in const signed int LBSTATE12, __in const signed int LBSTATE13, __in const signed int LBSTATE14)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_CharacterEvent 20

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_CharacterEvent];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &CharacterId, sizeof(CharacterId));
    EventDataDescCreate(&EventData[4], &Score, sizeof(Score));
    EventDataDescCreate(&EventData[5], &LBSTATE00, sizeof(LBSTATE00));
    EventDataDescCreate(&EventData[6], &LBSTATE01, sizeof(LBSTATE01));
    EventDataDescCreate(&EventData[7], &LBSTATE02, sizeof(LBSTATE02));
    EventDataDescCreate(&EventData[8], &LBSTATE03, sizeof(LBSTATE03));
    EventDataDescCreate(&EventData[9], &LBSTATE04, sizeof(LBSTATE04));
    EventDataDescCreate(&EventData[10], &LBSTATE05, sizeof(LBSTATE05));
    EventDataDescCreate(&EventData[11], &LBSTATE06, sizeof(LBSTATE06));
    EventDataDescCreate(&EventData[12], &LBSTATE07, sizeof(LBSTATE07));
    EventDataDescCreate(&EventData[13], &LBSTATE08, sizeof(LBSTATE08));
    EventDataDescCreate(&EventData[14], &LBSTATE09, sizeof(LBSTATE09));
    EventDataDescCreate(&EventData[15], &LBSTATE10, sizeof(LBSTATE10));
    EventDataDescCreate(&EventData[16], &LBSTATE11, sizeof(LBSTATE11));
    EventDataDescCreate(&EventData[17], &LBSTATE12, sizeof(LBSTATE12));
    EventDataDescCreate(&EventData[18], &LBSTATE13, sizeof(LBSTATE13));
    EventDataDescCreate(&EventData[19], &LBSTATE14, sizeof(LBSTATE14));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[2], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_CharacterEvent, EventData);
}
#define EventEnabledCreationEvent() (TRUE)

// Entry point to log the event CreationEvent
//
__inline
ULONG
EventWriteCreationEvent(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int LastUpdateTick, __in const signed int LBSTATE00, __in const signed int LBSTATE01, __in const signed int LBSTATE02, __in const signed int LBSTATE03, __in const signed int LBSTATE04, __in const signed int LBSTATE05, __in const signed int LBSTATE06, __in const signed int LBSTATE07, __in const signed int LBSTATE08, __in const signed int LBSTATE09, __in const signed int LBSTATE10, __in const signed int LBSTATE11, __in const signed int LBSTATE12, __in const signed int LBSTATE13, __in const signed int LBSTATE14)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_CreationEvent 19

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_CreationEvent];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &LastUpdateTick, sizeof(LastUpdateTick));
    EventDataDescCreate(&EventData[4], &LBSTATE00, sizeof(LBSTATE00));
    EventDataDescCreate(&EventData[5], &LBSTATE01, sizeof(LBSTATE01));
    EventDataDescCreate(&EventData[6], &LBSTATE02, sizeof(LBSTATE02));
    EventDataDescCreate(&EventData[7], &LBSTATE03, sizeof(LBSTATE03));
    EventDataDescCreate(&EventData[8], &LBSTATE04, sizeof(LBSTATE04));
    EventDataDescCreate(&EventData[9], &LBSTATE05, sizeof(LBSTATE05));
    EventDataDescCreate(&EventData[10], &LBSTATE06, sizeof(LBSTATE06));
    EventDataDescCreate(&EventData[11], &LBSTATE07, sizeof(LBSTATE07));
    EventDataDescCreate(&EventData[12], &LBSTATE08, sizeof(LBSTATE08));
    EventDataDescCreate(&EventData[13], &LBSTATE09, sizeof(LBSTATE09));
    EventDataDescCreate(&EventData[14], &LBSTATE10, sizeof(LBSTATE10));
    EventDataDescCreate(&EventData[15], &LBSTATE11, sizeof(LBSTATE11));
    EventDataDescCreate(&EventData[16], &LBSTATE12, sizeof(LBSTATE12));
    EventDataDescCreate(&EventData[17], &LBSTATE13, sizeof(LBSTATE13));
    EventDataDescCreate(&EventData[18], &LBSTATE14, sizeof(LBSTATE14));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[3], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_CreationEvent, EventData);
}
#define EventEnabledCreationProgress() (TRUE)

// Entry point to log the event CreationProgress
//
__inline
ULONG
EventWriteCreationProgress(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const double PlayTime)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_CreationProgress 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_CreationProgress];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &PlayTime, sizeof(PlayTime));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[4], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_CreationProgress, EventData);
}
#define EventEnabledEnemyDefeated() (TRUE)

// Entry point to log the event EnemyDefeated
//
__inline
ULONG
EventWriteEnemyDefeated(__in_opt PCWSTR UserId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in LPCGUID RoundId, __in const signed int PlayerRoleId, __in const signed int PlayerWeaponId, __in const signed int EnemyRoleId, __in const signed int KillTypeId, __in const float LocationX, __in const float LocationY, __in const float LocationZ, __in const signed int EnemyWeaponId)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_EnemyDefeated 16

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_EnemyDefeated];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[3], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[4], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[6], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[7], RoundId, sizeof(GUID));
    EventDataDescCreate(&EventData[8], &PlayerRoleId, sizeof(PlayerRoleId));
    EventDataDescCreate(&EventData[9], &PlayerWeaponId, sizeof(PlayerWeaponId));
    EventDataDescCreate(&EventData[10], &EnemyRoleId, sizeof(EnemyRoleId));
    EventDataDescCreate(&EventData[11], &KillTypeId, sizeof(KillTypeId));
    EventDataDescCreate(&EventData[12], &LocationX, sizeof(LocationX));
    EventDataDescCreate(&EventData[13], &LocationY, sizeof(LocationY));
    EventDataDescCreate(&EventData[14], &LocationZ, sizeof(LocationZ));
    EventDataDescCreate(&EventData[15], &EnemyWeaponId, sizeof(EnemyWeaponId));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[5], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_EnemyDefeated, EventData);
}
#define EventEnabledGameProgress() (TRUE)

// Entry point to log the event GameProgress
//
__inline
ULONG
EventWriteGameProgress(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const float CompletionPercent)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_GameProgress 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_GameProgress];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &CompletionPercent, sizeof(CompletionPercent));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[6], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_GameProgress, EventData);
}
#define EventEnabledItemUsed() (TRUE)

// Entry point to log the event ItemUsed
//
__inline
ULONG
EventWriteItemUsed(__in_opt PCWSTR UserId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in const signed int ItemId, __in const float LocationX, __in const float LocationY, __in const float LocationZ)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_ItemUsed 11

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_ItemUsed];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[3], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[4], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[6], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[7], &ItemId, sizeof(ItemId));
    EventDataDescCreate(&EventData[8], &LocationX, sizeof(LocationX));
    EventDataDescCreate(&EventData[9], &LocationY, sizeof(LocationY));
    EventDataDescCreate(&EventData[10], &LocationZ, sizeof(LocationZ));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[7], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_ItemUsed, EventData);
}
#define EventEnabledMediaUsage() (TRUE)

// Entry point to log the event MediaUsage
//
__inline
ULONG
EventWriteMediaUsage(__in_opt PCWSTR AppSessionId, __in_opt PCWSTR AppSessionStartDateTime, __in const unsigned int UserIdType, __in_opt PCWSTR UserId, __in_opt PCWSTR SubscriptionTierType, __in_opt PCWSTR SubscriptionTier, __in_opt PCWSTR MediaType, __in_opt PCWSTR ProviderId, __in_opt PCWSTR ProviderMediaId, __in_opt PCWSTR ProviderMediaInstanceId, __in LPCGUID BingId, __in const unsigned __int64 MediaLengthMs, __in const unsigned int MediaControlAction, __in const float PlaybackSpeed, __in const unsigned __int64 MediaPositionMs, __in const unsigned __int64 PlaybackDurationMs, __in_opt PCWSTR AcquisitionType, __in_opt PCWSTR AcquisitionContext, __in_opt PCWSTR AcquisitionContextType, __in_opt PCWSTR AcquisitionContextId, __in const signed int PlaybackIsStream, __in const signed int PlaybackIsTethered, __in_opt PCWSTR MarketplaceLocation, __in_opt PCWSTR ContentLocale, __in const float TimeZoneOffset, __in const unsigned int ScreenState)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_MediaUsage 27

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_MediaUsage];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (AppSessionId != NULL) ? AppSessionId : L"", (AppSessionId != NULL) ? (ULONG)((wcslen(AppSessionId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], (AppSessionStartDateTime != NULL) ? AppSessionStartDateTime : L"", (AppSessionStartDateTime != NULL) ? (ULONG)((wcslen(AppSessionStartDateTime) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[3], &UserIdType, sizeof(UserIdType));
    EventDataDescCreate(&EventData[4], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], (SubscriptionTierType != NULL) ? SubscriptionTierType : L"", (SubscriptionTierType != NULL) ? (ULONG)((wcslen(SubscriptionTierType) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[6], (SubscriptionTier != NULL) ? SubscriptionTier : L"", (SubscriptionTier != NULL) ? (ULONG)((wcslen(SubscriptionTier) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[7], (MediaType != NULL) ? MediaType : L"", (MediaType != NULL) ? (ULONG)((wcslen(MediaType) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[8], (ProviderId != NULL) ? ProviderId : L"", (ProviderId != NULL) ? (ULONG)((wcslen(ProviderId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[9], (ProviderMediaId != NULL) ? ProviderMediaId : L"", (ProviderMediaId != NULL) ? (ULONG)((wcslen(ProviderMediaId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[10], (ProviderMediaInstanceId != NULL) ? ProviderMediaInstanceId : L"", (ProviderMediaInstanceId != NULL) ? (ULONG)((wcslen(ProviderMediaInstanceId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[11], BingId, sizeof(GUID));
    EventDataDescCreate(&EventData[12], &MediaLengthMs, sizeof(MediaLengthMs));
    EventDataDescCreate(&EventData[13], &MediaControlAction, sizeof(MediaControlAction));
    EventDataDescCreate(&EventData[14], &PlaybackSpeed, sizeof(PlaybackSpeed));
    EventDataDescCreate(&EventData[15], &MediaPositionMs, sizeof(MediaPositionMs));
    EventDataDescCreate(&EventData[16], &PlaybackDurationMs, sizeof(PlaybackDurationMs));
    EventDataDescCreate(&EventData[17], (AcquisitionType != NULL) ? AcquisitionType : L"", (AcquisitionType != NULL) ? (ULONG)((wcslen(AcquisitionType) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[18], (AcquisitionContext != NULL) ? AcquisitionContext : L"", (AcquisitionContext != NULL) ? (ULONG)((wcslen(AcquisitionContext) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[19], (AcquisitionContextType != NULL) ? AcquisitionContextType : L"", (AcquisitionContextType != NULL) ? (ULONG)((wcslen(AcquisitionContextType) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[20], (AcquisitionContextId != NULL) ? AcquisitionContextId : L"", (AcquisitionContextId != NULL) ? (ULONG)((wcslen(AcquisitionContextId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[21], &PlaybackIsStream, sizeof(PlaybackIsStream));
    EventDataDescCreate(&EventData[22], &PlaybackIsTethered, sizeof(PlaybackIsTethered));
    EventDataDescCreate(&EventData[23], (MarketplaceLocation != NULL) ? MarketplaceLocation : L"", (MarketplaceLocation != NULL) ? (ULONG)((wcslen(MarketplaceLocation) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[24], (ContentLocale != NULL) ? ContentLocale : L"", (ContentLocale != NULL) ? (ULONG)((wcslen(ContentLocale) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[25], &TimeZoneOffset, sizeof(TimeZoneOffset));
    EventDataDescCreate(&EventData[26], &ScreenState, sizeof(ScreenState));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[8], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_MediaUsage, EventData);
}
#define EventEnabledMissionProgress() (TRUE)

// Entry point to log the event MissionProgress
//
__inline
ULONG
EventWriteMissionProgress(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed __int64 EarnedGold, __in const double PlayTime)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_MissionProgress 5

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_MissionProgress];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &EarnedGold, sizeof(EarnedGold));
    EventDataDescCreate(&EventData[4], &PlayTime, sizeof(PlayTime));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[9], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_MissionProgress, EventData);
}
#define EventEnabledMultiplayerRoundEnd() (TRUE)

// Entry point to log the event MultiplayerRoundEnd
//
__inline
ULONG
EventWriteMultiplayerRoundEnd(__in_opt PCWSTR UserId, __in LPCGUID RoundId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int MatchTypeId, __in const signed int DifficultyLevelId, __in const float TimeInSeconds, __in const signed int ExitStatusId)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_MultiplayerRoundEnd 11

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_MultiplayerRoundEnd];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], RoundId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[4], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[5], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[6], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[7], &MatchTypeId, sizeof(MatchTypeId));
    EventDataDescCreate(&EventData[8], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[9], &TimeInSeconds, sizeof(TimeInSeconds));
    EventDataDescCreate(&EventData[10], &ExitStatusId, sizeof(ExitStatusId));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[10], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_MultiplayerRoundEnd, EventData);
}
#define EventEnabledMultiplayerRoundStart() (TRUE)

// Entry point to log the event MultiplayerRoundStart
//
__inline
ULONG
EventWriteMultiplayerRoundStart(__in_opt PCWSTR UserId, __in LPCGUID RoundId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int MatchTypeId, __in const signed int DifficultyLevelId)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_MultiplayerRoundStart 9

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_MultiplayerRoundStart];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], RoundId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[4], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[5], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[6], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[7], &MatchTypeId, sizeof(MatchTypeId));
    EventDataDescCreate(&EventData[8], &DifficultyLevelId, sizeof(DifficultyLevelId));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[11], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_MultiplayerRoundStart, EventData);
}
#define EventEnabledObjectiveEnd() (TRUE)

// Entry point to log the event ObjectiveEnd
//
__inline
ULONG
EventWriteObjectiveEnd(__in_opt PCWSTR UserId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in const signed int ObjectiveId, __in const signed int ExitStatusId)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_ObjectiveEnd 9

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_ObjectiveEnd];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[3], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[4], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[6], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[7], &ObjectiveId, sizeof(ObjectiveId));
    EventDataDescCreate(&EventData[8], &ExitStatusId, sizeof(ExitStatusId));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[12], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_ObjectiveEnd, EventData);
}
#define EventEnabledObjectiveStart() (TRUE)

// Entry point to log the event ObjectiveStart
//
__inline
ULONG
EventWriteObjectiveStart(__in_opt PCWSTR UserId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in const signed int ObjectiveId)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_ObjectiveStart 8

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_ObjectiveStart];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[3], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[4], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[6], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[7], &ObjectiveId, sizeof(ObjectiveId));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[13], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_ObjectiveStart, EventData);
}
#define EventEnabledPageAction() (TRUE)

// Entry point to log the event PageAction
//
__inline
ULONG
EventWritePageAction(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int ActionTypeId, __in const signed int ActionInputMethodId, __in_opt PCWSTR Page, __in_opt PCWSTR TemplateId, __in_opt PCWSTR DestinationPage, __in_opt PCWSTR Content)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_PageAction 9

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_PageAction];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &ActionTypeId, sizeof(ActionTypeId));
    EventDataDescCreate(&EventData[4], &ActionInputMethodId, sizeof(ActionInputMethodId));
    EventDataDescCreate(&EventData[5], (Page != NULL) ? Page : L"", (Page != NULL) ? (ULONG)((wcslen(Page) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[6], (TemplateId != NULL) ? TemplateId : L"", (TemplateId != NULL) ? (ULONG)((wcslen(TemplateId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[7], (DestinationPage != NULL) ? DestinationPage : L"", (DestinationPage != NULL) ? (ULONG)((wcslen(DestinationPage) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[8], (Content != NULL) ? Content : L"", (Content != NULL) ? (ULONG)((wcslen(Content) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[14], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_PageAction, EventData);
}
#define EventEnabledPageView() (TRUE)

// Entry point to log the event PageView
//
__inline
ULONG
EventWritePageView(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR Page, __in_opt PCWSTR RefererPage, __in const signed int PageTypeId, __in_opt PCWSTR PageTags, __in_opt PCWSTR TemplateId, __in_opt PCWSTR Content)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_PageView 9

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_PageView];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (Page != NULL) ? Page : L"", (Page != NULL) ? (ULONG)((wcslen(Page) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[4], (RefererPage != NULL) ? RefererPage : L"", (RefererPage != NULL) ? (ULONG)((wcslen(RefererPage) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], &PageTypeId, sizeof(PageTypeId));
    EventDataDescCreate(&EventData[6], (PageTags != NULL) ? PageTags : L"", (PageTags != NULL) ? (ULONG)((wcslen(PageTags) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[7], (TemplateId != NULL) ? TemplateId : L"", (TemplateId != NULL) ? (ULONG)((wcslen(TemplateId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[8], (Content != NULL) ? Content : L"", (Content != NULL) ? (ULONG)((wcslen(Content) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[15], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_PageView, EventData);
}
#define EventEnabledPlayerDefeated() (TRUE)

// Entry point to log the event PlayerDefeated
//
__inline
ULONG
EventWritePlayerDefeated(__in_opt PCWSTR UserId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in LPCGUID RoundId, __in const signed int PlayerRoleId, __in const signed int PlayerWeaponId, __in const signed int EnemyRoleId, __in const signed int EnemyWeaponId, __in const float LocationX, __in const float LocationY, __in const float LocationZ)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerDefeated 15

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerDefeated];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[3], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[4], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[6], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[7], RoundId, sizeof(GUID));
    EventDataDescCreate(&EventData[8], &PlayerRoleId, sizeof(PlayerRoleId));
    EventDataDescCreate(&EventData[9], &PlayerWeaponId, sizeof(PlayerWeaponId));
    EventDataDescCreate(&EventData[10], &EnemyRoleId, sizeof(EnemyRoleId));
    EventDataDescCreate(&EventData[11], &EnemyWeaponId, sizeof(EnemyWeaponId));
    EventDataDescCreate(&EventData[12], &LocationX, sizeof(LocationX));
    EventDataDescCreate(&EventData[13], &LocationY, sizeof(LocationY));
    EventDataDescCreate(&EventData[14], &LocationZ, sizeof(LocationZ));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[16], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerDefeated, EventData);
}
#define EventEnabledPlayerMatchEvent() (TRUE)

// Entry point to log the event PlayerMatchEvent
//
__inline
ULONG
EventWritePlayerMatchEvent(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int PlayerMatchTotalPlayNum)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerMatchEvent 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerMatchEvent];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &PlayerMatchTotalPlayNum, sizeof(PlayerMatchTotalPlayNum));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[17], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerMatchEvent, EventData);
}
#define EventEnabledPlayerSessionEnd() (TRUE)

// Entry point to log the event PlayerSessionEnd
//
__inline
ULONG
EventWritePlayerSessionEnd(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in const signed int ExitStatusId)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSessionEnd 7

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSessionEnd];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[4], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[5], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[6], &ExitStatusId, sizeof(ExitStatusId));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[18], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSessionEnd, EventData);
}
#define EventEnabledPlayerSessionPause() (TRUE)

// Entry point to log the event PlayerSessionPause
//
__inline
ULONG
EventWritePlayerSessionPause(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSessionPause 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSessionPause];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[19], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSessionPause, EventData);
}
#define EventEnabledPlayerSessionResume() (TRUE)

// Entry point to log the event PlayerSessionResume
//
__inline
ULONG
EventWritePlayerSessionResume(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSessionResume 6

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSessionResume];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[4], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[5], &DifficultyLevelId, sizeof(DifficultyLevelId));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[20], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSessionResume, EventData);
}
#define EventEnabledPlayerSessionStart() (TRUE)

// Entry point to log the event PlayerSessionStart
//
__inline
ULONG
EventWritePlayerSessionStart(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSessionStart 6

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSessionStart];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[4], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[5], &DifficultyLevelId, sizeof(DifficultyLevelId));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[21], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSessionStart, EventData);
}
#define EventEnabledPlayerSpawned() (TRUE)

// Entry point to log the event PlayerSpawned
//
__inline
ULONG
EventWritePlayerSpawned(__in_opt PCWSTR UserId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in LPCGUID RoundId, __in const signed int PlayerRoleId, __in const float LocationX, __in const float LocationY, __in const float LocationZ)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSpawned 12

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSpawned];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[3], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[4], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[6], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[7], RoundId, sizeof(GUID));
    EventDataDescCreate(&EventData[8], &PlayerRoleId, sizeof(PlayerRoleId));
    EventDataDescCreate(&EventData[9], &LocationX, sizeof(LocationX));
    EventDataDescCreate(&EventData[10], &LocationY, sizeof(LocationY));
    EventDataDescCreate(&EventData[11], &LocationZ, sizeof(LocationZ));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[22], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_PlayerSpawned, EventData);
}
#define EventEnabledPresenceEvent() (TRUE)

// Entry point to log the event PresenceEvent
//
__inline
ULONG
EventWritePresenceEvent(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR PresenceString)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_PresenceEvent 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_PresenceEvent];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], (PresenceString != NULL) ? PresenceString : L"", (PresenceString != NULL) ? (ULONG)((wcslen(PresenceString) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[23], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_PresenceEvent, EventData);
}
#define EventEnabledRankmatchEvent() (TRUE)

// Entry point to log the event RankmatchEvent
//
__inline
ULONG
EventWriteRankmatchEvent(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int LargeRegion, __in const signed int Score, __in const signed int LBSTATE00, __in const signed int LBSTATE01, __in const signed int LBSTATE02, __in const signed int LBSTATE03, __in const signed int LBSTATE04, __in const signed int LBSTATE05, __in const signed int LBSTATE06, __in const signed int LBSTATE07, __in const signed int LBSTATE08, __in const signed int LBSTATE09, __in const signed int LBSTATE10, __in const signed int LBSTATE11, __in const signed int LBSTATE12, __in const signed int LBSTATE13, __in const signed int LBSTATE14)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_RankmatchEvent 20

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_RankmatchEvent];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &LargeRegion, sizeof(LargeRegion));
    EventDataDescCreate(&EventData[4], &Score, sizeof(Score));
    EventDataDescCreate(&EventData[5], &LBSTATE00, sizeof(LBSTATE00));
    EventDataDescCreate(&EventData[6], &LBSTATE01, sizeof(LBSTATE01));
    EventDataDescCreate(&EventData[7], &LBSTATE02, sizeof(LBSTATE02));
    EventDataDescCreate(&EventData[8], &LBSTATE03, sizeof(LBSTATE03));
    EventDataDescCreate(&EventData[9], &LBSTATE04, sizeof(LBSTATE04));
    EventDataDescCreate(&EventData[10], &LBSTATE05, sizeof(LBSTATE05));
    EventDataDescCreate(&EventData[11], &LBSTATE06, sizeof(LBSTATE06));
    EventDataDescCreate(&EventData[12], &LBSTATE07, sizeof(LBSTATE07));
    EventDataDescCreate(&EventData[13], &LBSTATE08, sizeof(LBSTATE08));
    EventDataDescCreate(&EventData[14], &LBSTATE09, sizeof(LBSTATE09));
    EventDataDescCreate(&EventData[15], &LBSTATE10, sizeof(LBSTATE10));
    EventDataDescCreate(&EventData[16], &LBSTATE11, sizeof(LBSTATE11));
    EventDataDescCreate(&EventData[17], &LBSTATE12, sizeof(LBSTATE12));
    EventDataDescCreate(&EventData[18], &LBSTATE13, sizeof(LBSTATE13));
    EventDataDescCreate(&EventData[19], &LBSTATE14, sizeof(LBSTATE14));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[24], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_RankmatchEvent, EventData);
}
#define EventEnabledReplayEvent() (TRUE)

// Entry point to log the event ReplayEvent
//
__inline
ULONG
EventWriteReplayEvent(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed int LastUpdateTick, __in const signed int LBSTATE00, __in const signed int LBSTATE01, __in const signed int LBSTATE02, __in const signed int LBSTATE03, __in const signed int LBSTATE04, __in const signed int LBSTATE05, __in const signed int LBSTATE06, __in const signed int LBSTATE07, __in const signed int LBSTATE08, __in const signed int LBSTATE09, __in const signed int LBSTATE10, __in const signed int LBSTATE11, __in const signed int LBSTATE12, __in const signed int LBSTATE13, __in const signed int LBSTATE14)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_ReplayEvent 19

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_ReplayEvent];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &LastUpdateTick, sizeof(LastUpdateTick));
    EventDataDescCreate(&EventData[4], &LBSTATE00, sizeof(LBSTATE00));
    EventDataDescCreate(&EventData[5], &LBSTATE01, sizeof(LBSTATE01));
    EventDataDescCreate(&EventData[6], &LBSTATE02, sizeof(LBSTATE02));
    EventDataDescCreate(&EventData[7], &LBSTATE03, sizeof(LBSTATE03));
    EventDataDescCreate(&EventData[8], &LBSTATE04, sizeof(LBSTATE04));
    EventDataDescCreate(&EventData[9], &LBSTATE05, sizeof(LBSTATE05));
    EventDataDescCreate(&EventData[10], &LBSTATE06, sizeof(LBSTATE06));
    EventDataDescCreate(&EventData[11], &LBSTATE07, sizeof(LBSTATE07));
    EventDataDescCreate(&EventData[12], &LBSTATE08, sizeof(LBSTATE08));
    EventDataDescCreate(&EventData[13], &LBSTATE09, sizeof(LBSTATE09));
    EventDataDescCreate(&EventData[14], &LBSTATE10, sizeof(LBSTATE10));
    EventDataDescCreate(&EventData[15], &LBSTATE11, sizeof(LBSTATE11));
    EventDataDescCreate(&EventData[16], &LBSTATE12, sizeof(LBSTATE12));
    EventDataDescCreate(&EventData[17], &LBSTATE13, sizeof(LBSTATE13));
    EventDataDescCreate(&EventData[18], &LBSTATE14, sizeof(LBSTATE14));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[25], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_ReplayEvent, EventData);
}
#define EventEnabledSectionEnd() (TRUE)

// Entry point to log the event SectionEnd
//
__inline
ULONG
EventWriteSectionEnd(__in_opt PCWSTR UserId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId, __in const signed int ExitStatusId)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_SectionEnd 8

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_SectionEnd];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[3], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[4], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[6], &DifficultyLevelId, sizeof(DifficultyLevelId));
    EventDataDescCreate(&EventData[7], &ExitStatusId, sizeof(ExitStatusId));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[26], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_SectionEnd, EventData);
}
#define EventEnabledSectionStart() (TRUE)

// Entry point to log the event SectionStart
//
__inline
ULONG
EventWriteSectionStart(__in_opt PCWSTR UserId, __in const signed int SectionId, __in LPCGUID PlayerSessionId, __in_opt PCWSTR MultiplayerCorrelationId, __in const signed int GameplayModeId, __in const signed int DifficultyLevelId)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_SectionStart 7

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_SectionStart];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], &SectionId, sizeof(SectionId));
    EventDataDescCreate(&EventData[3], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[4], (MultiplayerCorrelationId != NULL) ? MultiplayerCorrelationId : L"", (MultiplayerCorrelationId != NULL) ? (ULONG)((wcslen(MultiplayerCorrelationId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[5], &GameplayModeId, sizeof(GameplayModeId));
    EventDataDescCreate(&EventData[6], &DifficultyLevelId, sizeof(DifficultyLevelId));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[27], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_SectionStart, EventData);
}
#define EventEnabledVersusProgress() (TRUE)

// Entry point to log the event VersusProgress
//
__inline
ULONG
EventWriteVersusProgress(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in const signed __int64 PlayNum)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_VersusProgress 4

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_VersusProgress];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], &PlayNum, sizeof(PlayNum));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[28], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_VersusProgress, EventData);
}
#define EventEnabledViewOffer() (TRUE)

// Entry point to log the event ViewOffer
//
__inline
ULONG
EventWriteViewOffer(__in_opt PCWSTR UserId, __in LPCGUID PlayerSessionId, __in LPCGUID OfferGuid, __in LPCGUID ProductGuid)
{
#define ARGUMENT_COUNT_NBGI_22CB4DAA_ViewOffer 5

    EVENT_DATA_DESCRIPTOR EventData[ARGUMENT_COUNT_NBGI_22CB4DAA_ViewOffer];
    UINT8 scratch[64];

    EtxFillCommonFields_v7(&EventData[0], scratch, 64);

    EventDataDescCreate(&EventData[1], (UserId != NULL) ? UserId : L"", (UserId != NULL) ? (ULONG)((wcslen(UserId) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L""));
    EventDataDescCreate(&EventData[2], PlayerSessionId, sizeof(GUID));
    EventDataDescCreate(&EventData[3], OfferGuid, sizeof(GUID));
    EventDataDescCreate(&EventData[4], ProductGuid, sizeof(GUID));

    return EtxEventWrite(&NBGI_22CB4DAAEvents[29], &NBGI_22CB4DAAProvider, NBGI_22CB4DAAHandle, ARGUMENT_COUNT_NBGI_22CB4DAA_ViewOffer, EventData);
}
#if defined(__cplusplus)
};
#endif

#pragma pack(pop)
